### ISSUE TITLE
Cannot find module 'node:fs'

### ISSUE THREAD

**Issue by xqin** [kucherenko/blamer#29]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

```
Cannot find module 'node:fs'
Require stack:
- /tmp/.npm/_npx/66/lib/node_modules/jscpd/node_modules/blamer/build/main/vcs/git.js
- /tmp/.npm/_npx/66/lib/node_modules/jscpd/node_modules/blamer/build/main/blamer.js
- /tmp/.npm/_npx/66/lib/node_modules/jscpd/node_modules/blamer/build/main/index.js
- /tmp/.npm/_npx/66/lib/node_modules/jscpd/node_modules/@jscpd/finder/dist/hooks/blamer.js
- /tmp/.npm/_npx/66/lib/node_modules/jscpd/node_modules/@jscpd/finder/dist/hooks/index.js
- /tmp/.npm/_npx/66/lib/node_modules/jscpd/node_modules/@jscpd/finder/dist/index.js
- /tmp/.npm/_npx/66/lib/node_modules/jscpd/dist/index.js
- /tmp/.npm/_npx/66/lib/node_modules/jscpd/bin/jscpd
```

https://github.com/kucherenko/blamer/blame/2ca7c28bdd8d31bb7d8bd33e8a637c456476a853/src/vcs/git.ts#L4

node version:  v14.16.1

https://nodejs.org/api/esm.html#node-imports

`node:imports` only support by `node >=v14.18.0  >=v16.0.0`

<img width="636" alt="image" src="https://github.com/kucherenko/blamer/assets/1265888/30ebb1b5-70eb-48e7-b18f-434323e54eef">

For compatibility with lower versions, please adjust the way the module is introduced. Thank you very much.

**Comment by kucherenko** [comment]
fixed at blamer@1.0.6
